### ISSUE TITLE
请问预训练模型是哪一个

### ISSUE THREAD

**Issue by LEPZHANG** [nwpuhkp/FCN_VOC2012_Pytorch#1]
请问第467行的model（model.load_state_dict(torch.load('./model/fcn8s_epoch0.pt')) # 导入网络的参数）是https://github.com/pytorch/vision/tree/main/torchvision/models/segmentation这个repo中的fcn.py预训练模型吗

**Comment by k4pl3r** [comment]
你好，这个是个人训练的时候的模型，我暂时还没确认预训练网络模型是否一样，所以不太确定预训练pth能否直接使用

**Comment by LEPZHANG** [comment]
好的，谢谢您。那请问哪里可以有用的fcn8s.pth，因为我看见他们那个repo更新过了，只有py文件了。

**Comment by k4pl3r** [comment]
这个暂时还不太清楚，pytorch好像是现在都改为在hub中集成的模式了

**Comment by LEPZHANG** [comment]
好的 谢谢您
